name: 'Run Playwright Tests'

on:
  workflow_run:
    workflows: [ 'Publish to CloudFlare Pages' ]
    types:
      - completed

jobs:
  playwright:
    name: 'Run Playwright Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Setup node & cache'
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.1'
          cache: 'yarn'
      - name: 'Install dependencies'
        run: |
          yarn policies set-version
          yarn set version 4.0.2
          yarn --frozen-lockfile
      - name: 'Run Playwright tests'
        env:
          PLAYWRIGHT_BASE_URL: ${{ secrets.PLAYWRIGHT_BASE_URL }}
          PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}
          PLAYWRIGHT_SERVICE_ACCESS_TOKEN: ${{ secrets.PLAYWRIGHT_SERVICE_ACCESS_TOKEN }}
          PLAYWRIGHT_SERVICE_RUN_ID: ${{ github.run_id }}-${{ github.run_attempt }}-${{ github.sha }}
        run: yarn playwright:run --config=playwright.service.config.ts --workers=50
      - name: 'Save Test Reports'
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-report
          path: __tests__/report
          retention-days: 30