name: 'Publish to CloudFlare Pages (Preview)'
on:
  pull_request:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: "Publish to Cloudflare Pages (Preview) & Run E2E Tests"
    steps:
      - uses: actions/checkout@v4
      - name: 'Setup node & cache'
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.1'
          cache: 'yarn'
      - name: 'Install dependencies'
        run: |
          yarn policies set-version
          yarn set version 4.0.2
          yarn --frozen-lockfile
      - name: 'Build the application'
        run: yarn build
      - name: 'Publish to Cloudflare Pages (Preview)'
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: playwright-showcase
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
      - name: 'Run Playwright tests'
        env:
          PLAYWRIGHT_BASE_URL: ${{ steps.deploy.outputs.url }}
          PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}
          PLAYWRIGHT_SERVICE_ACCESS_TOKEN: ${{ secrets.PLAYWRIGHT_SERVICE_ACCESS_TOKEN }}
          PLAYWRIGHT_SERVICE_RUN_ID: ${{ github.run_id }}-${{ github.run_attempt }}-${{ github.sha }}
        run: yarn playwright:run --config=playwright.service.config.ts --workers=50
      - name: 'Save Test Reports'
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-report
          path: __tests__/report
          retention-days: 30